services:
  - type: web
    name: phonebook-backend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
